name: JupyterKernel
version: 1.5.0
date: 2023-02-25
description: |
    Jupyter kernel written in GAP

authors:
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/
    - name: Manuel Martins
      url: https://github.com/mcmartins

maintainers:
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: The GAP Team
      url: mailto:support@gap-system.org

contributors:
    - name: Thomas Breuer
    - name: Pedro García-Sánchez
    - name: Sebastian Gutsche
    - name: Max Horn
    - name: Fernando Isuru
    - name: Zachariah Newbery
    - name: Sergio Siccha

GAP: ">= 4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "io"
      version: ">= 4.5.4"
      url: "https://gap-packages.github.io/io"
    - name: "json"
      version: ">= 2.0.0"
      url: "https://gap-packages.github.io/json/"
    - name: "uuid"
      version: ">= 0.6"
      url: "https://gap-packages.github.io/uuid/"
    - name: "ZeroMQInterface"
      version: ">= 0.10"
      url: "https://gap-packages.github.io/ZeroMQInterface/"
    - name: "crypting"
      version: ">= 0.9"
      url: "https://gap-packages.github.io/crypting/"

www: https://gap-packages.github.io/JupyterKernel/
readme: README.md
packageinfo: https://gap-packages.github.io/JupyterKernel/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/JupyterKernel/releases/download/v1.5.0/JupyterKernel-1.5.0.tar.gz

abstract: |
    The <span class="pkgname">JupyterKernel</span> package provides a so-called kernel for the Jupyter interactive document system.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Jupyter, User Interface.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PMKT23</span>]   <b class='BibAuthor'>Pfeiffer, M., Martins, M., Konovalov, O. and GAP Team, T.</b>,
     <i class='BibTitle'>JupyterKernel, Jupyter kernel written in GAP,
             Version 1.5.0</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/JupyterKernel/">https://gap-packages.github.io/JupyterKernel/</a></span>.
    </p>
    

bibtex: |
    @misc{ JupyterKernel1.5.0,
      author =           {Pfeiffer, M. and Martins, M. and Konovalov, O. and GAP
                          Team, T.},
      title =            {{JupyterKernel},   Jupyter   kernel  written  in  GAP,
                          {V}ersion 1.5.0},
      month =            {Feb},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href  {https://gap-packages.github.io/JupyterKernel/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{JupyterKernel/}}},
      keywords =         {Jupyter; User Interface},
      printedkey =       {PMKT23}
    }

