name: JupyterKernel
version: 0.5
date: 2018-05-28
description: |
    Jupyter kernel written in GAP

authors:
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/

maintainers:
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "io"
      version: ">= 4.4.6"
      url: "https://gap-packages.github.io/io"
    - name: "json"
      version: ">= 1.1.0"
      url: "https://gap-packages.github.io/json/"
    - name: "uuid"
      version: ">= 0.4"
      url: "https://gap-packages.github.io/uuid/"
    - name: "ZeroMQInterface"
      version: ">= 0.8"
      url: "https://gap-packages.github.io/ZeroMQInterface/"
    - name: "crypting"
      version: ">= 0.7"
      url: "https://gap-packages.github.io/crypting/"

www: http://gap-packages.github.io/JupyterKernel/
readme: README.md
packageinfo: http://gap-packages.github.io/JupyterKernel/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/JupyterKernel/releases/download/v0.5/JupyterKernel-0.5.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
